### ISSUE TITLE
`password_cmd` with other than linux pass

### ISSUE THREAD

**Issue by juliangaal** [Spotifyd/spotifyd#385]
I'm trying to use `password_cmd` with the [bitwarden cli](https://help.bitwarden.com/article/cli/)

```ini
[global]
username =  <REDACTED>
# password = PASS
password_cmd = "bw get password Spotify"  # can be used as alternative to `password`
# use_keyring = true                                     # can be used as alternative to `password`
backend = alsa                                           # run `spotifyd --backends` for possible values
device = alsa_audio_device                               # run `aplay -L` for possible values
# control = alsa_audio_device                            # device for the mixer, if not the same as 'device'
mixer = PCM
volume_controller = alsa                                    # or alsa_linear, or softvol
# on_song_change_hook = command_to_run_on_playback_events
device_name = device_name_in_spotify_connect             # must not contain spaces
bitrate = 160                                            # or 96, or 320
cache_path = cache_directory
no_audio_cache = true                                    # use credentials-only caching
volume_normalisation = true
normalisation_pregain = -10
zeroconf_port = port_number
```
tried with 

I'm getting this error:
```bash
07:22:19 [INFO] Loading config from "/home/juliangaal/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("invalid digit found in string")', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: spotifyd::config::CliConfig::load_config_file_values
  10: spotifyd::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start
```

which happens somewhere in your [custom ini comment part](https://github.com/Spotifyd/spotifyd/blob/f89626571eb50b196069e11ff479ede670302816/src/config.rs#L385) I think. 2 Questions: 
* why the custom ini? Doesn't `toml-rs` handle comments out of the box and toml looks nearly identical to your ini syntax?
* which special characters does rust have an issue with here? 

Thanks!

**Comment by SirWindfield** [comment]
The format, as of now, is INI. Switching to TOML is actually a breaking change, as values have to be denoted with strings, e.g. `password_cmd = "pass ..."`.

I am on the same boat though, TOML is better than INI (especially because it has a clear specifications whereas INI doesn't). I tried to stay away from breaking changes as long as possible.

Your problem might be solved by leaving out the quotes as they are not needed. Not sure if that is the source of the problem though.

Do you get more output by running it in debug mode (without the `--release` flag) and by setting `RUST_BACKTRACE=1`?

**Comment by juliangaal** [comment]
my bad :/ copy past error on my side...`zeroconf_port` must be a number, obviously. Sorry for wasting your time

**Comment by SirWindfield** [comment]
Nah, no time wasted :)
