### ISSUE TITLE
Error Launching - Unknown Variant "alsa" expected values ("alsa")

### ISSUE THREAD

**Issue by tcanabrava** [Spotifyd/spotifyd#896]
```
[global]
username = "bleh"
password = "bleh"
use_mpris = true
backend = "alsa"
device = "alsa_audio_device"  # omit for macOS
control = "alsa_audio_device"  # omit for macOS
mixer = "PCM"
volume_controller = "alsa"  # use softvol for macOS
device_name = "tomaz_desktop"
bitrate = 160
cache_path = "/data/spotify"
no_audio_cache = false
initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10
device_type = "computer"

```
```
~ ⌚ 12:17:22
$ spotifyd --no-daemon                
Loading config from "/home/tcanabrava/.config/spotifyd/spotifyd.conf"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("unknown variant `\"alsa\"`, expected one of `alsa`, `portaudio`, `pulseaudio`, `rodio`")', /home/tcanabrava/.cargo/registry/src/github.com-1ecc6299db9ec823/spotifyd-0.2.24/src/config.rs:415:85
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: spotifyd::config::CliConfig::load_config_file_values
   4: spotifyd::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by robinvd** [comment]
i cannot reproduce the error with the config you provided. I think i have seen this error before when the new config is used with an old version (< 0.3). Are you sure you are using 0.3?

**Comment by oczkers** [comment]
Just unquote alsa
"alsa" -> alsa
